# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsp < Formula
  desc "Easily switch between AWS Profiles with an interactive selector"
  homepage "https://github.com/abyss/go-awsp"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abyss/go-awsp/releases/download/v1.1.0/go-awsp_Darwin_x86_64.tar.gz"
      sha256 "6bdaf11bb1acf3f8c0c473b9e08606ab9fb55c76d4c4fe293fb34ceef0ddb29f"

      define_method(:install) do
        prefix.install "awsp"
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abyss/go-awsp/releases/download/v1.1.0/go-awsp_Darwin_arm64.tar.gz"
      sha256 "3e77ae34dd08e07adfaeee66cdd2c8f661d6a2c4f60635834a9c23c652ba9eba"

      define_method(:install) do
        prefix.install "awsp"
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/go-awsp/releases/download/v1.1.0/go-awsp_Linux_x86_64.tar.gz"
      sha256 "5ea86b0fc2b82dd82ab1cb96461589808bc915310ad87d52c5a68b082092d847"
      define_method(:install) do
        prefix.install "awsp"
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/go-awsp/releases/download/v1.1.0/go-awsp_Linux_arm64.tar.gz"
      sha256 "790c71006f4137bbf63f66a1bb87b2e4bbaf2468a09709962ef8a2cf9fa80671"
      define_method(:install) do
        prefix.install "awsp"
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
  end

  def caveats
    <<~EOS
      ##################################################################

      To use awsp, add the following to your shell profile:
          alias awsp='. awsp'

      ##################################################################
    EOS
  end
end
