# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plan < Formula
  desc "Plan Journal CLI - Manage daily plan files organized by month"
  homepage "https://github.com/abyss/plan-journal-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.0/plan-journal-cli_Darwin_x86_64.tar.gz"
      sha256 "000f8061203b576c9d39a4a6b0c8d73e431ccb24867591d96e4907ffb940fff4"

      def install
        bin.install "plan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.0/plan-journal-cli_Darwin_arm64.tar.gz"
      sha256 "9ed50347bb91e5bab0c3726eab6692e3e4e60f1cf7fb3555f602bbde3b81d107"

      def install
        bin.install "plan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.0/plan-journal-cli_Linux_x86_64.tar.gz"
      sha256 "8a3fc1190c5479b4a31d096f7aee4a04bb3229491aa3ed5857fb65b435329dfc"
      def install
        bin.install "plan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.0/plan-journal-cli_Linux_arm64.tar.gz"
      sha256 "af3efad11138ab5a8b8b2203deae67ff9cce5a132cbb310769f5138e6adf38ae"
      def install
        bin.install "plan"
      end
    end
  end
end
