# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plan < Formula
  desc "Plan Journal CLI - Manage daily plan files organized by month"
  homepage "https://github.com/abyss/plan-journal-cli"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.3/plan-journal-cli_Darwin_x86_64.tar.gz"
      sha256 "95bb8ac54a774a339837881c362f5ec2e9eca0e932973a6ffa4121b9e01bc8bc"

      define_method(:install) do
        bin.install "plan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.3/plan-journal-cli_Darwin_arm64.tar.gz"
      sha256 "8613982057015c3fdc43c77bbe5469fafeea5826246b5cf5dbc0fb451ef9f491"

      define_method(:install) do
        bin.install "plan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.3/plan-journal-cli_Linux_x86_64.tar.gz"
      sha256 "9a1d0fd48d49c59ee4c9695bef8b67adc753654d598e1319b36b7f6353631ff3"
      define_method(:install) do
        bin.install "plan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/plan-journal-cli/releases/download/v1.0.3/plan-journal-cli_Linux_arm64.tar.gz"
      sha256 "386cb747f08dce391d6c6aad3d08996e15bb3dc5077b44910ffcde6a7f4f11af"
      define_method(:install) do
        bin.install "plan"
      end
    end
  end
end
