# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfwand < Formula
  desc "tfwand — OpenTofu/Terraform utility toolkit"
  homepage "https://github.com/abyss/tfwand"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abyss/tfwand/releases/download/v0.2.0/tfwand_Darwin_x86_64.tar.gz"
      sha256 "f71e6d77c05d62b114e1c56d44b91ddd46bef3758a55ff7bfa340ba406432ca9"

      define_method(:install) do
        bin.install "wand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abyss/tfwand/releases/download/v0.2.0/tfwand_Darwin_arm64.tar.gz"
      sha256 "6977b8983048f1222f25218a595d5167244a5d08cbcc79977f32c965bafdff69"

      define_method(:install) do
        bin.install "wand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/tfwand/releases/download/v0.2.0/tfwand_Linux_x86_64.tar.gz"
      sha256 "a8d6cb37fa5d7453a5356ec04b5e62cfecce280fc96372aa2a7095e8f7905805"
      define_method(:install) do
        bin.install "wand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/tfwand/releases/download/v0.2.0/tfwand_Linux_arm64.tar.gz"
      sha256 "c972740285dd773dfa9fa8eaf1de4027bc45561c8da6558797df18502ddde8dc"
      define_method(:install) do
        bin.install "wand"
      end
    end
  end
end
