# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfwand < Formula
  desc "tfwand — OpenTofu/Terraform utility toolkit"
  homepage "https://github.com/abyss/tfwand"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abyss/tfwand/releases/download/v0.3.1/tfwand_Darwin_x86_64.tar.gz"
      sha256 "734ba09c09a765dbbeef9752c77a92e1ed31c7340e64df1c7468d77aff17aac7"

      define_method(:install) do
        bin.install "wand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abyss/tfwand/releases/download/v0.3.1/tfwand_Darwin_arm64.tar.gz"
      sha256 "fe60e2c3070b71d1355b6000038b923b93a8e40eec4e55ff6ecd11586baf38fd"

      define_method(:install) do
        bin.install "wand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/tfwand/releases/download/v0.3.1/tfwand_Linux_x86_64.tar.gz"
      sha256 "058859f86773947d84d2358acdf8a42483fcbe58c25d96aff4cbc356c82dfe2f"
      define_method(:install) do
        bin.install "wand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abyss/tfwand/releases/download/v0.3.1/tfwand_Linux_arm64.tar.gz"
      sha256 "be193dc5ebca12fd141b609ee4f0e21bd97a3403b88745c5d7e3ec86677bd8bc"
      define_method(:install) do
        bin.install "wand"
      end
    end
  end
end
